### ISSUE TITLE
add conda not found issue

### ISSUE THREAD

**Issue by Filippo1598** [diffpy/diffpy.labpdfproc#107]
![image](https://github.com/user-attachments/assets/20cabc28-9b5c-4cb0-b15c-4d4ce2cc25db)

**Comment by bobleesj** [comment]
not closed

**Comment by bobleesj** [comment]
<img width="499" alt="Screenshot 2024-10-15 at 2 46 17 PM" src="https://github.com/user-attachments/assets/c4653a6a-4b4b-41a5-b269-1f064a7c4d74">

@Filippo1598 This can be closed now.
