### ISSUE TITLE
Doc API package module not displayed

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.labpdfproc#110]
<img width="981" alt="image" src="https://github.com/user-attachments/assets/db74a569-46ca-4c5f-bc5e-4d0bd9c0512c">

https://www.diffpy.org/diffpy.labpdfproc/api/diffpy.labpdfproc.html

**Comment by bobleesj** [comment]
@yucongalicechen

**Comment by sbillinge** [comment]
closed as completed
