### ISSUE TITLE
figure out testing until Gooey is updated

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.labpdfproc#133]
See #130 for more details.

**Comment by bobleesj** [comment]
@yucongalicechen Hi Yucong, we have manually modified the CI to do `pip install` in the issue/PR here https://github.com/diffpy/diffpy.labpdfproc/issues/135. Could you please close this issue after you've checked that your PR https://github.com/diffpy/diffpy.labpdfproc/pull/130 provides a green check? You could do an empty commit like, `git commit --allow-empty -m "Re-run CI`

**Comment by yucongalicechen** [comment]
closed by #136
