### ISSUE TITLE
load the name of the package and the version number into metadata

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.labpdfproc#28]

**Comment by stevenhua0320** [comment]
###UC1 Package & version for individual file
0. Before executing any argument, LPP uses function (load_package_version) to load the package & Version 
1. CGS wants to use LPP with one file, but they are not sure if the package is complete for analysis or if the version of the package is satisfied. 

###UC2 Package & Version for multiple files
1. Much similar to 1.1, but "load_package_version" takes multiple files as arguments, each specifying different requirements for  package and version number for analysis.

**Comment by sbillinge** [comment]
Thanks this is great.  The UCs here are basically the same as for the timestamp.

UC1 is: a future group member wants to know which version of the code was used to analyze a particular dataset and reads the file header.

UC2 is: current user doesn't want to add any metadata because it is boring overhead to their work.

LPP satisfies this conflicting needs by doing it automatically.  @stevenhua0320 please can you edit the previous UCs to clean them up and have them reflect these?   Does that make sense to you?

**Comment by stevenhua0320** [comment]
Yes professor, I got your point about intent of loading package and version for different groups of users. I have reflected your UC in my first comment. Thanks, Professor.

**Comment by sbillinge** [comment]
> Yes professor, I got your point about intent of loading package and version for different groups of users. I have reflected your UC in my first comment. Thanks, Professor.

Thanks that was great.  I just cleaned it up a bit.

**Comment by sbillinge** [comment]
Thanks @stevenhua0320 we will use `importlib.metadata.version('labpdfproc')` to get the package version so to test it we will just have to mock that method.  @yucongalicechen can maybe help you if you are not sure.  This is straightforward so you can move ahead and start writing the code for htis one.  This can happen anywhere it makes sense in the code.

**Comment by stevenhua0320** [comment]
OK, I would try to implement the test and make PR.

**Comment by sbillinge** [comment]
I don't remember the package name exactly, whether we called it `diffpy.labpdfproc` but you can check by looking in the `pyproject.toml` file.

**Comment by sbillinge** [comment]
I don't think we have a group "style" on mocking atm, so we could use `unittest.mock` but since we are moving over to pytest pretty much then using `monkeypatch` in pytest is maybe best for the mocking.
