### ISSUE TITLE
load the datetime of the analysis into metadata

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.labpdfproc#29]

**Comment by stevenhua0320** [comment]
Here is a suggested UC
**UC 1 user searching for files**
chem grad student (CGS) wants to search for files that they worked on on Thursday afternoon.
CGS writes a quick script in jupyter that searches over files in a directory tree, obtains the datetime from the header and sorts appropriately, returning a list of files that pass the filter
In order for this UC to work we need another
**UC2 labpdfproc writing datetime to header**
User runs labpdfproc (LPP)
LPP successfully executes to compute a correction for each file
LPP adds the datetime to metadata before writing the output file
LPP adds the metadata to the file header
For testing we will need to have a fake datetime. We can do this by mocking datetime. The code will need to know whether it is a test running or not. There seem to be some hacky ways to do it but it may be better to be explicit and allow a --is-test CLI input that is false by default but can be set to true in all our tests.

**Comment by stevenhua0320** [comment]
For the datetime test, is there alternative way such as freeze time package? If we still use the way of  adds --is-test CLI input, is it set in the get_args function and when we would like to test it, we switch it to True?

**Comment by sbillinge** [comment]
I am open to any suggested solution, I don't have a great way of doing this, but yes, your description is correct.  We would have this in `get_args` with `set-true` property and we would add that flag to all our tests, but it would never be used by users.  It would need a help description saying that.

for the test I think we would need to mock datetime.datetime.now() to return a fixed datetime.

**Comment by yucongalicechen** [comment]
For the test I think you can use either a MagicMock or freezegun, so that you can manually set a current datetime. This would be for the test only and probably wouldn't interfere with the original program.
For UC 2.3 above (not sure if we need to address this here), but if we want to write datetime to metadata just before outputing file, we probably want to call load_datetime in the compute_cve function, right before we produce the absorption correction DO?

**Comment by sbillinge** [comment]
it looks like freezegun could be a good solution.  I have never used it before.

For when the time is determined, I think right before the file is written.

**Comment by sbillinge** [comment]
A problem I see here is that we are never giving the user the choice of
whether to save a datetime.  Where do you see that in the UCs?

**Comment by sbillinge** [comment]
Ah, I think I see, you are looking at the UC where some time in the future
someone wants to search for files.  This will not be handled by
labpdfprocit is just motivation for why we want to save datetime in the
files in the first place.  Summary: we are not implementing this here

**Comment by sbillinge** [comment]
Please read the UCs from the pressure p perspective of the user and try and
understand the intent (not implementation).  There is already too much
python syntax in what you are writing so I can tell your mind is in the
wrong place... Thinking about detailstoo much. This task is a high level
strategic task

**Comment by sbillinge** [comment]
In case it helps for example the first question is simply which UCs will we
implement right now? And the answer is a list of ucs

**Comment by stevenhua0320** [comment]
the first thing is to implement UC2, which is to set the attribute of creation_time for every successful output file. Is that right Professor?

**Comment by sbillinge** [comment]
Still too low level.  The first is to agree on the full list of ucs

**Comment by sbillinge** [comment]
Then the next week be a high level design that delivers all the
functionality in all those user cases as simply and elegantly as
possible... No python yet, could be written in any language.

**Comment by stevenhua0320** [comment]
OK, so first is that I need to see the issues from the user perspective that relates to the subject, know about the intent of what purpose of doing that(datetime for instance). Then think about how to implement it?

**Comment by sbillinge** [comment]
Yes, that is right.  You are not a user so ask Yucong and me questions when
you are not sure

**Comment by stevenhua0320** [comment]
OK, I would follow the procedure you recommend and ask questions related to UC as long as I come up with question.

**Comment by sbillinge** [comment]
Closing.  This is now handled by the functionality in `diffraction_object.dump`
