### ISSUE TITLE
Implement input files

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.labpdfproc#51]
The functionality works like this: first it looks for a file, then it looks for a directory and glob all files in it. It also accepts wild card and a file list (default file may be like input_file_list that contains a list of things to run on).

Examples:
lpd 2.5 jins_data.chi
lpd 2.5 ./input_dir/jins_data.chi
lpd 2.5 .
lpd 2.5 ./input_dir
lpd 2.5 *.chi
lpd 2.5 input_dir/*.chi
lpd 2.5 file1.chi file10.chi
lpd 2.5 input_file_list.txt

file1.chi 2.5
file2.chi 3.5 (multiple files with different muD)
-file7.chi (specify files don’t want to read)

**Comment by sbillinge** [comment]
I think I would put these as a comment with the original UCs issue so we can link to everything all together.  As I mentioned in another review, copy-paste the URL to that issue as a comment in the code so it is easy to find in the future.
