### ISSUE TITLE
add `--is-test` to all test commands

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.labpdfproc#61]
90% of tests will pass without the `--is-test` flag set, but for consistency, I suggest we add this to all the tests.  It will create less confusion in the future .

**Comment by stevenhua0320** [comment]
### UC 1 Tester of LPP test the app runs successfully
1. Tester of app runs LPP and set --is-test to True
2. A tester uses particular test files to determine if corresponding functions run without errors or potential bugs.

**Comment by sbillinge** [comment]
> ### UC 1 Tester of LPP test the app runs successfully
> 
>     1. Tester of app runs LPP and set --is-test to True
> 
>     2. A tester uses particular test files to determine if corresponding functions run without errors or potential bugs.

sorry, this is all very confusing.  We don't need a UC for the tests.  We are looking for pseudocode of the actual test functionality.  Sorry it is so confusing.  Thank you so much for your efforts to understand.  I know it is confusing.   UCs capture user behavior (no implementation information), pseudocode for hte test describe the actual code that will be written but not in real syntax.

**Comment by stevenhua0320** [comment]
OK, so for --is-test, since it is not for general users, here we directly consider its test function to consider its behavior right?

**Comment by sbillinge** [comment]
alternatively, since a goal is for that creation time to actually appear in the file, we could write a file and then check that the right time is in there.

On the whole, I think if we check that the right thing is loaded in args, and then later we make a test that checks that everything from args makes it into the file, this accomplishes the same thing

**Comment by sbillinge** [comment]
> OK, so for --is-test, since it is not for general users, here we directly consider its test function to consider its behavior right?

I am afraid I don't understand your question.  We may not need `--is-test` here actually if we use runfreeze.

**Comment by stevenhua0320** [comment]
Yes, that's what yucong and I previously thought about since for creation-time we may not use --is-test since we use freezegun to freeze time to test the datetime behavior. but for other cases, we might still use --is-test flags, so we might use it elsewhere.

**Comment by sbillinge** [comment]
> Yes, that's what yucong and I previously thought about since for creation-time we may not use --is-test since we use freezegun to freeze time to test the datetime behavior. but for other cases, we might still use --is-test flags, so we might use it elsewhere.

in that case it is not needed in this PR at all.

**Comment by sbillinge** [comment]
Let's hold on this until we are sure it is needed.  It is not something i want unless it is absolutely needed.

**Comment by sbillinge** [comment]
please review and close if need be

**Comment by yucongalicechen** [comment]
closed as not needed for now
