### ISSUE TITLE
Implement quick calculation

### ISSUE THREAD

**Issue by yucongalicechen** [diffpy/diffpy.labpdfproc#85]
(I can split the issues later if that's easier)
- In a "data" folder: (1) store precomputed data 1/cve for muD=1 (as an .xy file), (2) store coefficient list in a csv file.
- In a new module "fast_cve":
- (1) Define global variables: angles from 1-180 degrees, sparse dataset muD list and coefficient list, an interpolation function based on these coefficients.
- (2) A function (and its test function) that reads in the muD and uses the interpolation function to predict the cve curve, and interpolates it onto user's tth (similar to compute_cve in functions.py).
- (3) A function (and its test function) similar to apply_corr that returns the corrected intensities.
- In labpdfprocapp.py: change default behavior to using fast_cve but give an optional command -b to enable brute-force calculation (raise an error if muD < 0.5 or muD > 6?).

**Comment by sbillinge** [comment]
looks good.  let's call the module `fast_cve` maybe?

Default behavior should be to use fast_cve but command-line override to do brute-force calculation

Write tests with the functions, so not on a separate activity.

**Comment by yucongalicechen** [comment]
Sounds good! I edited the comment.

**Comment by yucongalicechen** [comment]
updated by issue #91, closed by #92.
